### ISSUE TITLE
Failing to get state of enterprise issues (or all other private repos)

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#110]
on issue:
[2021.1.9 - duplicate lines in `scylla --help`](https://github.com/scylladb/scylla-enterprise/issues/2183)
scylla-enterprise#2183
Error fetching state from Github: API Error

![image](https://user-images.githubusercontent.com/340979/165491019-ce31f4f4-b323-4def-8b59-eaf7cc6b81ab.png)

**Comment by k0machi** [comment]
Known issue, need to get authorization from scylla org to be able to read private issues
