### ISSUE TITLE
Add link to relocatable package in issue template

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#120]
Developers would appreciate link to relocatable package when we create an issue. E.g.:
http://downloads.scylladb.com/unstable/scylla/master/relocatable/2022-03-17T14:10:37Z/scylla-debug-x86_64-unified-package-5.1.dev.0.20220317.c45050895403.tar.gz for Scylla Version: 5.1.dev-20220317.c45050895403

To achieve that we can reuse dev's solution (of course using some python library):
```
build_id=076f513b6143670def988c7626389b270411f8f7; curl -s -X POST http://backtrace.scylladb.com/index.html -d "build_id=$build_id&backtrace=" | sed -En -e "/^$build_id/s:^.*http:http:" -e "/^http/s:</a>::p"
```

I can volunteer in implementing it.

**Comment by k0machi** [comment]
A good idea, I think for responsiveness reasons this should be done as an AJAX endpoint that is called when Issue Template is first opened
