### ISSUE TITLE
Hydra show log and hydra show monitor button are not working

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#143]
Hydra show log and hydra show monitor button are not working:

seems like `clipboard` is undefined for some reason
```js
TestRunInfo.svelte:181 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.<anonymous> (TestRunInfo.svelte:181:49)
```

```html
  <button
      type="button"
      class="btn btn-outline-success"
      on:click={() => {
          navigator.clipboard.writeText(
              cmd_hydraInvestigateShowMonitor
          );
      }}><Fa icon={faCopy} /> Hydra Show Monitor</button
  >
```

**Comment by fruch** [comment]
seem like: 
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by k0machi** [comment]
Indeed, this is a known issue until we get a domain name and an SSL certificate for our current instance.

**Comment by fruch** [comment]
> Indeed, this is a known issue until we get a domain name and an SSL certificate for our current instance.

can we implement it in other way, until we have the clipboard working ?

**Comment by k0machi** [comment]
We could make those buttons to be a "disabled" textbox instead that will autoselect contents on click, that could be a workaround - should check if `navigator.clipboard` is available and decide what to draw based on that.
