### ISSUE TITLE
Have an option to save more than the last 10 runs for specific jobs

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/argus#163]
Some jobs, namely the artifact ami jobs, run more than once when triggered. The base ami job specifically runs 15 times once it is triggered, which makes the 10 run history that argus saves insufficient.

Please add an option to save a history of more than 10 of the latest runs per job.

**Comment by k0machi** [comment]
I plan to implement this when working on refactoring `TestRuns` component - a button that allows you to load more runs for a test, in case you want to check the history, each consecutive press would add 10 more runs to the dash.

**Comment by fruch** [comment]
@k0machi isn't this done already?

**Comment by k0machi** [comment]
Looks like it
