### ISSUE TITLE
Cannot link issue

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#181]
In my staging job I cannot link issue
https://argus.scylladb.com/workspace?state=WyI3ZTJjZmNkNS02MGNiLTRmMDYtYTdmMi0xOGRkYmE4MDY2Y2IiXQ

The message box shows:
```
An error occurred.
API Error while submitting an issue on a test run. Message: None values on filter are not allowed
```

**Comment by fruch** [comment]
@soyacz 

Seen it since ?

If not, we can close it

**Comment by soyacz** [comment]
not any more. Closing
