### ISSUE TITLE
Empty row in 'my jobs' panel

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#184]
![image](https://user-images.githubusercontent.com/18242288/203325108-b0a1c271-12be-48b4-9d22-ef5da7e24784.png)
after checking with dev tools I noticed id:
`testRun_354fbd2d-0dbd-45cd-b3fa-592c86591d72`

**Comment by k0machi** [comment]
Could be related to #145, let's see if it reproduces after merging #191
