### ISSUE TITLE
A user should not receive a notification from tagging themselves

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/argus#197]
![Screenshot from 2022-12-27 18-20-21](https://user-images.githubusercontent.com/40186893/209693343-be8e1071-da8c-4216-ab9b-05d0fcb788f6.png)

On that note, maybe a user should not receive a notification if he was tagged inside of a quote

**Comment by fgelcer** [comment]
> ![Screenshot from 2022-12-27 18-20-21](https://user-images.githubusercontent.com/40186893/209693343-be8e1071-da8c-4216-ab9b-05d0fcb788f6.png)
> 
> On that note, maybe a user should not receive a notification if he was tagged inside of a quote

IMHO the user when tagging itself SHOULD YES receive a notification, as a kind of a bookmark to come back to some specific discussion later on

**Comment by ShlomiBalalis** [comment]
> > ![Screenshot from 2022-12-27 18-20-21](https://user-images.githubusercontent.com/40186893/209693343-be8e1071-da8c-4216-ab9b-05d0fcb788f6.png)
> > On that note, maybe a user should not receive a notification if he was tagged inside of a quote
> 
> IMHO the user when tagging itself SHOULD YES receive a notification, as a kind of a bookmark to come back to some specific discussion later on

Are you refering to tagging oneself or the other suggestion?

**Comment by fgelcer** [comment]
your issue subject says `A user should not receive a notification from tagging themselves` and i think it should... if you mention only when you reply to a comment, and it includes yourself in the response, then i don't care if it will notify me or not

**Comment by fruch** [comment]
@k0machi I do agree it's suppressing the couple of the first time it happens

**Comment by k0machi** [comment]
> @k0machi I do agree it's suppressing the couple of the first time it happens

I can set it to ignore if mention follows up with `posted:\n`, that should help with this issue
