### ISSUE TITLE
"Badly formed hexadecimal UUID string" error updating test run assignee or status

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/argus#198]
Trying to update assignee or status of the test run `№4` of the `upgrade-platform-k8s-eks` job (`operator-1-8`) here: https://argus.scylladb.com/workspace?state=WyJkMjgwOGYwNC1lOTIxLTQ2NWUtYThkNy0zY2JjMDY3NDQzZjciXQ

I get following error:

![Screenshot from 2023-01-03 19-32-01](https://user-images.githubusercontent.com/3796058/210411292-170fa9ce-c3b9-43cf-b923-742457844d5d.png)

**Comment by fruch** [comment]
@vponomaryov have you seen since ?

**Comment by vponomaryov** [comment]
Now this:
![Screenshot from 2023-12-21 08-38-43](https://github.com/scylladb/argus/assets/3796058/ec187631-8b3e-4752-8e68-32b521a35f2c)
