### ISSUE TITLE
No sign in Argus when failing CI on early stage

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#202]
When CI fails early (e.g. on get duration step, or soon on create sct-runner step) we don't see any sign of it in Argus. This may lead to omit investigation of such jobs as it won't be shown.

Request is to create Argus run despite of these errors.

**Comment by k0machi** [comment]
We have a task to decouple run creation from the sct runner stage into its own stage to prevent exactly this.

**Comment by k0machi** [comment]
We have a task to decouple run creation from the sct runner stage into its own stage to prevent exactly this.

**Comment by fruch** [comment]
This was already addressed in SCT
