### ISSUE TITLE
Reply button on notifications screen doesn't work

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#203]
When opening the notifications on Android chrome, replay button doesn't do anything.

**Comment by fruch** [comment]
I think it doesn't work in general

**Comment by k0machi** [comment]
> I think it doesn't work in general

Yes, that button should be hidden on that window (or we could make it redirect to run comments). Alternatively opening a modal window with an editor is also an option.

**Comment by k0machi** [comment]
We can add a modal reply window on the notification screen, since comment has everything to create the editor this should work
