### ISSUE TITLE
Please, add column "DC name" to resources list ("Resources" tab)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/argus#222]
Please, add column "DC name" to resources list ("Resources" tab).
We need it for multi DC tests - to know in which DC the instance is located.

Example:
https://argus.scylladb.com/test/1158bb3b-c12c-4c8c-a38f-d4492c398a4d/runs?additionalRuns[]=c4c3ee91-c03b-4dc9-9df9-4e1f42885db5

**Comment by fruch** [comment]
@k0machi please add to the board

Does this need some SCT change ? or API change ?

**Comment by k0machi** [comment]
> @k0machi please add to the board
> 
> Does this need some SCT change ? or API change ?

Both I think, optional dc_name in CloudResource UDT and client update to include that field for resource creation. SCT change would be minimal, just new parameter for `client.create_resource`
