### ISSUE TITLE
feature request: have a page with all the issues for the version with filtering and ordering ability

### ISSUE THREAD

**Issue by fgelcer** [scylladb/argus#231]
right of now, the list of all issues for a release is displayed at the top of the release's dashboard page, and there we don't have any ability to neither filter or sort, making it sometimes hard to use, when for example trying to list per repo, specific keywords....

i'm not sure what information we store today for the issues assigned to the release, but perhaps we have lots of data to give us more options to work it.

**Comment by fruch** [comment]
@k0machi 

We discussed a bit about usability of the issues list

I think it should handle it in that order

1) paging

2) sorting

3) filtering / search

Again, all done local at client end, till we have search indexing
