### ISSUE TITLE
Siren-tests plugin: Add the number of failures into the "details" tab

### ISSUE THREAD

**Issue by rayakurl** [scylladb/argus#266]
For siren-tests plugin, need to add the number of failures of the job, as displayed in the "test results" tab in Jenkins (see attached screenshot)

![Screenshot from 2023-07-25 11-11-29](https://github.com/scylladb/argus/assets/97890133/e533c4aa-8020-4d5e-b732-57dfd54b0237)

**Comment by rayakurl** [comment]
@roydahan , @temichus - this is an easy fix that will help us a lot

**Comment by roydahan** [comment]
P2, not for this sprint.
