### ISSUE TITLE
Add the ability to open issues to "siren", "siren-frontend" and "siren-devops"

### ISSUE THREAD

**Issue by rayakurl** [scylladb/argus#267]
For the "Issues" tab - we need to add the Cloud repositories as well.
We have 3 potential repositores:
https://github.com/scylladb/siren
https://github.com/scylladb/siren-frontend
https://github.com/scylladb/siren-devops

order wise it should be: siren-frontend, siren, siren-devops 

For "siren" and "siren-frontend" repositories you can use the same template as in siren report, the bug flow: https://github.com/scylladb/siren/issues/new?assignees=&labels=bug&projects=&template=bug-report.md&title=

With a small change to the first section:
`
### What environment are you running on?

- [ ] Lab
- [ ] AppQA
- [ ] Staging
- [ ] Production
- [ ] Local

`
For "siren-devops" we don't need any template at all

**Comment by rayakurl** [comment]
@temichus , @roydahan - FYI

**Comment by roydahan** [comment]
P3 - not for this sprint.
