### ISSUE TITLE
artifacts instance type is wrong

### ISSUE THREAD

**Issue by fgelcer** [scylladb/argus#272]
looking into [this build](https://argus.scylladb.com/test/a6986b80-c879-4c33-a0db-7987f7b6a88f/runs?additionalRuns[]=cd02399c-4956-4b50-82bf-cbb94dbea9fb) i see that Argus is reporting the instance type to be `i3.large`, while it is in fact (from Jenkins parameter of that build) `im4gn.xlarge`

**Comment by ShlomiBalalis** [comment]
@temichus

**Comment by temichus** [comment]
this is an issue In SCT in "Create Argus Test run" Jenkins step https://github.com/scylladb/scylla-cluster-tests/issues/6370

**Comment by temichus** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/6458

**Comment by temichus** [comment]
@fgelcer Plases verify and close this issue.

**Comment by fgelcer** [comment]
> @fgelcer Plases verify and close this issue.

is it for new tests only, or previous tests will also have the right instance type?

**Comment by ShlomiBalalis** [comment]
> > @fgelcer Plases verify and close this issue.
> 
> is it for new tests only, or previous tests will also have the right instance type?

Considering it's an sct fix, I doubt it will change existing ones. Also, it didn't change any of the ones I just checked

**Comment by fgelcer** [comment]
> @fgelcer Plases verify and close this issue.

confirmed it worked in [this run](https://argus.scylladb.com/test/f5f76221-b454-4dd3-a91a-133678511161/runs?additionalRuns[]=a39ffd76-8960-446f-8eec-904bf46ecc97)
