### ISSUE TITLE
When using a version tag to filter jobs in the dashboard, some builds are missing

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/argus#273]
In 2022.1.9, we recently encountered a situation where, due to relying on version tags, a job failure was missed:

![Screenshot from 2023-07-26 19-25-30](https://github.com/scylladb/argus/assets/40186893/10d3e9f8-ea47-4089-9d6b-30e7171a31e1)
![Screenshot from 2023-07-26 19-25-52](https://github.com/scylladb/argus/assets/40186893/9c2c11e0-7ae8-478e-9c8f-e87f56330615)

The reason that the failed job build did not appear when using the tag is because the build failed before the scylla version was able to be reported:
![Screenshot from 2023-07-26 19-44-40](https://github.com/scylladb/argus/assets/40186893/4fe2bc47-acdf-4043-9d5b-a5e43c0fa98e)

We need to find a way to report to argus the scylla version even in such situations

**Comment by ShlomiBalalis** [comment]
Some option I thought of - the job is triggered with an ami. We can grab the scylla version from the aws tags

**Comment by fgelcer** [comment]
> Some option I thought of - the job is triggered with an ami. We can grab the scylla version from the aws tags

in this case, it is an AMI, but what about other artifacts that use a repository URL? i'm not sure, but maybe inside the repo URL path we have the version too?

**Comment by roydahan** [comment]
I think that we should display in the filter the version that match and all the runs with "missing" version.
Ugly, but safer.

**Comment by roydahan** [comment]
@temichus & @k0machi we need to find a way to fix it with high priority.
It's causing people to miss failures for patch releases.

**Comment by fgelcer** [comment]
one way of fixing it is to get the version from the AMI tag, repo link (it has the version inside the URL somewhere), or relocatable package

**Comment by roydahan** [comment]
> one way of fixing it is to get the version from the AMI tag, repo link (it has the version inside the URL somewhere), or relocatable package

This is not safe enough and I don't like it.

**Comment by ShlomiBalalis** [comment]
> > one way of fixing it is to get the version from the AMI tag, repo link (it has the version inside the URL somewhere), or relocatable package
> 
> This is not safe enough and I don't like it.

It can be just a precaution. ONLY if the job failed before reporting on any version, and only then, argus will try to extract the verison from those options

**Comment by fgelcer** [comment]
> > > one way of fixing it is to get the version from the AMI tag, repo link (it has the version inside the URL somewhere), or relocatable package
> > 
> > 
> > This is not safe enough and I don't like it.
> 
> It can be just a precaution. ONLY if the job failed before reporting on any version, and only then, argus will try to extract the verison from those options

or the opposite... we start from it, and update from the Scylla binary result of `--version`, so in case the test fails before we get the Scylla version, we will have some "basic" version reporting for each test build

**Comment by roydahan** [comment]
In summary if we can have a quick fix that shows the filtered version together with anything that has "no version"
