### ISSUE TITLE
driver-matrix tests report errors on sending results to Argus

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#277]
In java driver tests, recently we don't send results at all (branch 5.2, I don't know the others), failing on some dependencies installation:
https://jenkins.scylladb.com/job/scylla-5.2/job/driver-tests/job/java-driver-matrix-test/25/

In python-driver-matrix test we can see `argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/testrun/driver-matrix-tests/05f6d40f-6472-4a39-b4dd-aba45bad4139/set_status', 'This method is obsolete. Status is now determined on submission.')` errors (https://jenkins.scylladb.com/job/scylla-5.2/job/driver-tests/job/python-driver-matrix-test/18/)
the same is for cpp driver tests (https://jenkins.scylladb.com/job/scylla-5.2/job/driver-tests/job/cpp-driver-matrix-test/19/)
But at least we can see some results in Argus for these.

**Comment by k0machi** [comment]
This was due to #286, Java results were over default 1MB size limit, which is now fixed. The legacy endpoint exception will not prevent result submission.

**Comment by soyacz** [comment]
ok, this one no longer is problematic.
But still results are not uploaded to Argus. Can you check why?
