### ISSUE TITLE
event request is too big - need to be increased

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#286]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

```
2023-09-24 05:25:26,338 f:tester.py       l:538  c:LongevityTest        p:ERROR &gt; argus.client.base.ArgusClientError: ('Unexpected HTTP Response encountered - expected: 200, got: 413', 200, 413, &lt;PreparedRequest [POST]
```
413 is Request Too Large, I'll increase the POST limit to around 30MB on the server-side.

## Impact

it's happens from time to time

## How frequently does it reproduce?

happens more then once 

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `5.4.0~dev-20230921.a56a4b6226e6` with build-id `616f734e7c7fb5e3ee8898792b3c415d2574a132`

Cluster size: 12 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- parallel-topology-schema-changes-mu-db-node-780b13ee-9 (35.177.85.159 | 10.3.11.48) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-8 (3.10.9.117 | 10.3.11.226) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-7 (13.40.111.105 | 10.3.9.211) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-6 (3.250.117.111 | 10.4.8.183) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-5 (34.244.195.236 | 10.4.9.154) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-4 (52.213.136.156 | 10.4.10.188) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-3 (3.252.241.112 | 10.4.9.216) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-20 (3.250.88.54 | 10.4.8.203) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-2 (34.245.229.54 | 10.4.9.43) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-19 (18.169.106.10 | 10.3.8.166) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-18 (3.8.193.212 | 10.3.10.92) (shards: -1)
- parallel-topology-schema-changes-mu-db-node-780b13ee-17 (13.40.116.25 | 10.3.11.16) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-16 (34.249.244.10 | 10.4.8.193) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-15 (3.250.44.183 | 10.4.10.149) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-14 (34.244.206.6 | 10.4.9.78) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-13 (34.244.23.58 | 10.4.10.118) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-12 (18.168.226.135 | 10.3.8.178) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-11 (13.40.13.45 | 10.3.9.5) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-10 (13.40.140.198 | 10.3.11.191) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-780b13ee-1 (54.74.189.5 | 10.4.10.166) (shards: 7)

OS / Image: `ami-00f051bf1c684c01a ami-02f60844c6765bc4e` (aws: undefined_region)

Test: `longevity-multidc-schema-topology-changes-12h-test`
Test id: `780b13ee-33e7-4a3d-96e7-fcb18202d446`
Test name: `scylla-master/longevity/longevity-multidc-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-multidc-parallel-topology-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/558925b49a60a15952f3cbb0f692a73e50e7e058/test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 780b13ee-33e7-4a3d-96e7-fcb18202d446`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=780b13ee-33e7-4a3d-96e7-fcb18202d446)
- Show all stored logs command: `$ hydra investigate show-logs 780b13ee-33e7-4a3d-96e7-fcb18202d446`

## Logs:
- **db-cluster-780b13ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/db-cluster-780b13ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/db-cluster-780b13ee.tar.gz)
- **sct-runner-events-780b13ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/sct-runner-events-780b13ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/sct-runner-events-780b13ee.tar.gz)
- **sct-780b13ee.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/sct-780b13ee.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/sct-780b13ee.log.tar.gz)
- **loader-set-780b13ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/loader-set-780b13ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/loader-set-780b13ee.tar.gz)
- **monitor-set-780b13ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/monitor-set-780b13ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/780b13ee-33e7-4a3d-96e7-fcb18202d446/20230924_052539/monitor-set-780b13ee.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-multidc-schema-topology-changes-12h-test/13/)
[Argus](https://argus.scylladb.com/test/4d9b162e-c35a-41e6-a0ac-d677a64c26ac/runs?additionalRuns[]=780b13ee-33e7-4a3d-96e7-fcb18202d446)
</details>

**Comment by k0machi** [comment]
Fixed, size increased to 50MB in nginx.
