### ISSUE TITLE
stats: Performance bottleneck on stats / overview dashboards

### ISSUE THREAD

**Issue by k0machi** [scylladb/argus#293]
Currently, there's a serious performance bottleneck calculating statistics for each release page. We can introduce caching via either separate key-value storages like Redis (in-memory only) or via a separate table that's easier to query. This should solve performance bottlenecks on stats queries as it's a very long query that doesn't need to be ran on every request, and standard HTTP server caching isn't enough as user can force a request to go through, causing potentially massive slowdown if he has multiple tabs that do this request to happen.

We could also separate stats query as currently it not only fetches the latest run, but also does a bit of history in the form of also fetching last 5 runs. However problem here is runs that are part of a larger job, e.g. rolling upgrade or perf read/write/mixed

**Comment by roydahan** [comment]
Require a discussion, understanding the severity of the issue and what are the low hanging fruits we can do before introducing a caching solution.

**Comment by roydahan** [comment]
We should define the flow of reloading items in the screen, so we won't need to load all releases in parallel or some improvements that we can do according to a normal user flow.

**Comment by roydahan** [comment]
Let's start with scheduling a discussion of me, @fruch and @k0machi for next sprint to define what we want.
And later we will handle the task in next sprints.

**Comment by k0machi** [comment]
#323 Improves performance by caching for a longer period of time along with less eager fetches and some performance optimizations such as reducing amount of queries on certain pages going at the same time.

One more thing left to maybe is to cache stat calculating in-memory and timestamp/etag the stats object, only updating it when it gets invalidated by a run status change/submission, which could also be handled by backend.

**Comment by fruch** [comment]
> [#323](https://github.com/scylladb/argus/pull/323) Improves performance by caching for a longer period of time along with less eager fetches and some performance optimizations such as reducing amount of queries on certain pages going at the same time.
> 
> One more thing left to maybe is to cache stat calculating in-memory and timestamp/etag the stats object, only updating it when it gets invalidated by a run status change/submission, which could also be handled by backend.

let open up an issue for this next possible step

closing this one
