### ISSUE TITLE
Argus login - degraded mode or OAuth with Github App auth

### ISSUE THREAD

**Issue by k0machi** [scylladb/argus#297]
Since Github Apps potentially provide finer permission control than normal OAuth flow we should switch to it to reduce the power of tokens granted to Argus.

**Comment by roydahan** [comment]
@fruch / @k0machi let's start by estimating what's the quickest / lowest effort approach.
E.g. having a degraded mode for people who didn't authorize Argus, so they won't be able to see the issue status.
Or the full solution through Github Apps or whatever.

**Comment by k0machi** [comment]
@roydahan If the github app flow is largely the same it should be a quick fix - I'll provide the estimation soon.

**Comment by k0machi** [comment]
Okay, so the flow is a bit different - it would require changing authentication/token rotation logic. However moving to a github app will allow finer grained permissions (org only with issue/pr read access only to specific repositories - something that isn't possible with OAuth flow). 

For a quick fix we can implement a checkbox on the login page that says "Grant access to private repositories" and a hint that says that this will grant access to ALL your repositories.

**Comment by fruch** [comment]
> Okay, so the flow is a bit different - it would require changing authentication/token rotation logic. However moving to a github app will allow finer grained permissions (org only with issue/pr read access only to specific repositories - something that isn't possible with OAuth flow).
> 
> For a quick fix we can implement a checkbox on the login page that says "Grant access to private repositories" and a hint that says that this will grant access to ALL your repositories.

we need estimate for both things, to figure out which is first

**Comment by k0machi** [comment]
> we need estimate for both things, to figure out which is first

Checkbox is quick, can do that in a day, The second one would take a week at least.

**Comment by k0machi** [comment]
Looking at the "degraded" mode it seems that everything is functioning as is... I'm talking to Boris so we can move the argus app from my account to scylla and that might cover issues for private repos (which are apparently currently bork regardless)

**Comment by k0machi** [comment]
https://github.com/scylladb/argus/pull/311

**Comment by k0machi** [comment]
Issue panel when using the degraded experience:



![Image](https://github.com/scylladb/argus/assets/7761415/1f4a5275-952d-47b0-9272-441ac7149e73)

**Comment by fruch** [comment]
Schedule with boris to transfer the argus application

**Comment by k0machi** [comment]
Sent an email to @BorishuV regarding transfer of the application.

**Comment by k0machi** [comment]
Transfer done, also created test github app to investigate whether or not we should switch to that and also removed old argus-testers group as we don't need it anymore.

**Comment by roydahan** [comment]
What's left in this task?

**Comment by fruch** [comment]
@k0machi 

please open a new task for the GitApp work, i'm closing this cause we have the degraded mode
