### ISSUE TITLE
not all users can attach issues to a test build

### ISSUE THREAD

**Issue by fgelcer** [scylladb/argus#298]
here is an example image below, to @denesb 's user

![image (3)](https://github.com/scylladb/argus/assets/32832995/aaec5abe-8d95-4698-902b-a2aaa8619d99)

**Comment by k0machi** [comment]
> here is an example image below, to @denesb 's user
> 

Can you add the output of the browser's console? Seems like the widget is crashing here

**Comment by denesb** [comment]
I see this related error in the console:
```
Uncaught (in promise) RangeError: invalid date
    c GithubIssue.svelte:180
    c GithubIssue.svelte:208
    oe index.mjs:2090
    c GithubIssues.svelte:146
    p GithubIssues.svelte:145
    At index.mjs:1347
    Ot index.mjs:1307
    promise callback*Nt index.mjs:1258
    ctx index.mjs:2133
    ctx index.mjs:2171
    p GithubIssues.svelte:33
    j GithubIssues.svelte:87
    r index.mjs:20
    re index.mjs:2101
    Ot index.mjs:1329
    promise callback*Nt index.mjs:1258
    ctx index.mjs:2133
    ctx index.mjs:2171
    Gn TestRun.svelte:181
    B index.mjs:463
    m TestRun.svelte:282
    p TestRun.svelte:82
    At index.mjs:1347
    Ot index.mjs:1307
    promise callback*Nt index.mjs:1258
    ctx index.mjs:2133
    ctx index.mjs:2171
    E TestRun.svelte:39
    Gn TestRun.svelte:67
    r index.mjs:20
    re index.mjs:2101
    Ot index.mjs:1329
    promise callback*Nt index.mjs:1258
    ctx index.mjs:2133
    ctx index.mjs:2171
    D TestRuns.svelte:155
    J TestRuns.svelte:257
    r index.mjs:20
    re index.mjs:2101
    Ot index.mjs:1329
    ae index.mjs:2197
    ee TestRuns.svelte:376
    6021 test-runs-standalone.js:3
    Webpack 6
GithubIssue.svelte:180:56
```

**Comment by denesb** [comment]
![image](https://github.com/scylladb/argus/assets/1389273/f19bad15-6e65-4c8c-a818-81d5d103573f)
Note that I also see `InvalidDate` as start and end times of the job.

**Comment by k0machi** [comment]
> ![image](https://user-images.githubusercontent.com/1389273/281406655-f19bad15-6e65-4c8c-a818-81d5d103573f.png) Note that I also see `InvalidDate` as start and end times of the run.

Ah I see, there's a firefox bug currently regarding date parsing, you can try using chrome for now, I'll push #194 to high priority.
