### ISSUE TITLE
Usability enhancement  - Add ability to open a "Not Run" job - to show a link to its Jenkins job

### ISSUE THREAD

**Issue by roydahan** [scylladb/argus#307]
At the moment when you click "Investigate" on a "Not Run" job, you get the screen to "Select a layout", but it won't show anything.
The enhancement here is to display the link to the Jenkins job (we should already have this information), so one can click it and run that specific job from Jenkins.

In terms of implementation (as much as I understand it), maybe we can set it as the default layout for any job and when we have results for the relevant layout, it will override it.

In terms of UI, the simplest UI to just show the link to the jenkins job.

**Comment by roydahan** [comment]
@k0machi please let me know if it's clear and "simple" as I assume it is :)
Also, please try to add your eastimation.

**Comment by k0machi** [comment]
> @k0machi please let me know if it's clear and "simple" as I assume it is :) Also, please try to add your eastimation.

![image](https://github.com/scylladb/argus/assets/7761415/5931004a-f24d-458a-96df-267b4fd014a9)

If I understand it correctly - it's pretty simple to do as we already store jenkins url.
