### ISSUE TITLE
Allow 'Rebuild' of a Jenkins job directly from Argus

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#310]
Argus already has all the parameters. Sometimes, since there's an infra issues, I just want to re-run the job with the same parameters. A simple button on Argus can simplify this process.

**Comment by fruch** [comment]
It would save only one click.

I don't want it to be blind, without the user seeing the parameters being used.

So can have a button to get you straight into the rebuild page 

In half of the cases, some of the parameters used were wrong, doing it blindly would just keep at it

**Comment by roydahan** [comment]
Handling as part of this qa-task - https://github.com/scylladb/qa-tasks/issues/1612.
removing from project, we can use the issue just for the commit message closure.

**Comment by k0machi** [comment]
#344 completes this.
