### ISSUE TITLE
Auto refresh - Argus should do auto refresh by defaults for everything in the workspace area

### ISSUE THREAD

**Issue by roydahan** [scylladb/argus#313]
Currently it seems that Argus is periodically auto refreshing the entire screen.
We can easily improve performance by:
1. Have a manual button to refresh the left tree (for new tests, groups, stats, releases).
2. For the right pane (the investigate job screen) we can leave it to auto-refresh every X seconds (preferably configurable by user, in that case it could be off by default)
3. If there is a way to detect that the screen is in the background, argus shouldn't do a background refresh.

**Comment by fruch** [comment]
@k0machi please link here the relevert PRs

Or copy this into the relevert task, and close as duplicate

**Comment by k0machi** [comment]
For settings we may want to do a separate task to introduce some kind of preferences page, so that user can configure all application settings in one place.

**Comment by k0machi** [comment]
PR for everything else is https://github.com/scylladb/argus/pull/323
