### ISSUE TITLE
5.4 dashboard shows additional builds - 5.5.0-dev, 5.2.10, 5.2.11

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#315]
https://argus.scylladb.com/dashboard/scylla-5.4 shows:

![image](https://github.com/scylladb/argus/assets/4655593/a648fdc8-489a-4f74-9655-c33be6f84bb4)

**Comment by mykaul** [comment]
@k0machi ? @roydahan ? any explanation?

**Comment by k0machi** [comment]
> @k0machi ? @roydahan ? any explanation? 

Most likely rolling upgrade runs

**Comment by roydahan** [comment]
@k0machi there is a usability issue that we can’t easily find which are the “offending” runs.

In theory we shouldn’t have some of the above there and I wanted to check where they came from but couldn’t.

we need a way to include/exclude runs that have “No version”.
By default it can be always on, so one wouldn’t miss failures like we had in the past.

**Comment by k0machi** [comment]
Can add a checkbox for that if you want to have "No Version" always included

**Comment by mykaul** [comment]
In a way, what I'd be looking to filter is also 'latest runs which were not investigated' - so I don't care that much if something was run on 2024.1-rc1 or -rc2 - if the latest run was not investigated, that would be a useful filter for me.

**Comment by roydahan** [comment]
> Can add a checkbox for that if you want to have "No Version" always included

Let's start with that, sounds quick and easy enough.
The use case of releasing a RC and/or patch release is where you need it the most.

For filtering of all "not investigated" runs, which is a different use case, I think I have an idea, but I'll take it in another place.

**Comment by k0machi** [comment]
Okay, so if I understand correctly the original issue, there should be a way to hide versions that are not "latest", i.e. ones currently visible on the Dashboard view? For example, if `5.2.10` happened long time ago on that screenshot and is currently like run `#9` out of 80 that already happened, then it should be hidden, is that correct?

@mykaul

**Comment by roydahan** [comment]
@k0machi lets discuss this.
There are several use cases here and I'm not sure what would be the best solution.
