### ISSUE TITLE
Need to add FAILED-INFRA vs. FAILED-BUG (and perhaps FAILED-TEST) failures

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#316]
Right now, it's quite impossible to measure how stable our infra is, our tests are solid and how many bugs we actually encouter.
The dashboard today does not allow us to easily distinguished between failure modes. If we look at 5.4 right now, it look catastrophic, and I don't believe that's the case: 
![image](https://github.com/scylladb/argus/assets/4655593/147094cd-6289-4e1e-957e-bd8db134eccf)

44% failure is terrible! But we know it's inaccurate, since a failure could be of either causes. We need more granularity.

**Comment by k0machi** [comment]
Some SCT related changes would be required (and other infras still need to have full API implemented for them, like #289)

**Comment by mykaul** [comment]
> Some SCT related changes would be required (and other infras still need to have full API implemented for them, like #289)

Unsure why - the decision on failure is on the engineer investigating the run, no? I don't care the initial one to be FAILED-BUG, as long as I can manually move it to FAILED-INFRA.

**Comment by k0machi** [comment]
> > Some SCT related changes would be required (and other infras still need to have full API implemented for them, like #289)
> 
> Unsure why - the decision on failure is on the engineer investigating the run, no? I don't care the initial one to be FAILED-BUG, as long as I can manually move it to FAILED-INFRA.

Ah, in that case it would be simpler, I was thinking we could actually catch infra failure (for example Spot Termination Error) vs test failure (The current "Failed" indicator logic)

**Comment by mykaul** [comment]
In the future, sure - we can catch spot termination for example. That's future.

**Comment by fruch** [comment]
Anyhow I'm calling @roydahan opinion on it as well

**Comment by roydahan** [comment]
There is no such thing as Failed - infra. If something failed due to infra issue, it needs to be solved and rerun.
Hence there is no point to hold such a state.

**Comment by mykaul** [comment]
> There is no such thing as Failed - infra. If something failed due to infra issue, it needs to be solved and rerun. Hence there is no point to hold such a state.

How you you classify spot termination then?

**Comment by roydahan** [comment]
I classify them as failed and one need to rerun them.
It's not entering the statistics anyway, only the last run is part of the statistics you see in the top bar.

**Comment by fruch** [comment]
@roydahan 

again, we do want this state, but let's agree first on it's name (i.e. you didn't like failed-infra), we are open to suggestion

**Comment by roydahan** [comment]
We would like to have instead of "Failed-Infra", "Test Error".
This can be introduced now, later I would like it to automatically be set with failures we will define, like:
"SpotTermination".
