### ISSUE TITLE
PASSED tests are marked as 'Not investigated'

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#317]
See https://argus.scylladb.com/workspace?state=WyJiMmQyMzc4ZC05OTE0LTRjYjUtOTJkMy0wZDM5NzNiNTk2YTAiXQ for example. It makes no sense - we don't trust the results?
Please make sure those are marked as investigated, or can be ignored when looking if all runs of a test were looked at or not.

**Comment by fruch** [comment]
@k0machi is fixing it

So far we use this as a way of people seeing or not in their my jobs.

Passed has nothing to investigate, so it wasn't touched 

But now if it shows on some stats, that someone is looking, it can be updated as such.

**Comment by roydahan** [comment]
I don't think we should have done this.
There is a separation between the status and the investigation status.
And this is on purpose.
In theory a passed run should also been investigated, to make sure that everything is as expected and we can trust the result.

For example, a run could pass but it was using the wrong version or didn't have nemesis at all or had some warnings that are troublesome.

It would have been better if we know that these runs were looked at or not.

**Comment by fruch** [comment]
> I don't think we should have done this. There is a separation between the status and the investigation status. And this is on purpose. In theory a passed run should also been investigated, to make sure that everything is as expected and we can trust the result.
> 
> For example, a run could pass but it was using the wrong version or didn't have nemesis at all or had some warnings that are troublesome.
> 
> It would have been better if we know that these runs were looked at or not.

first, this change didn't yet merged.

no one would be verifying a passed test, in less there a some specific reason, and he'll do it cause of a real reason, not because of how it's mark on Argus. and if he finds an issue, he should mark it as failed, and attach the issue. 

changing this is purely cosmetic, either way.

**Comment by roydahan** [comment]
Right, but when there is a reason and you went to verify a passed test you can mark it as such. I did it several times.

And when you have a passed test that wasn't investigated and you came back to it due to an issue we may have missed, you know that no one has ever looked at this.

**Comment by mykaul** [comment]
I agree about the theory. In practice, no one investigates passed tests. It doesn't provide any value leaving them as 'not investigated' then. How else can I see that all runs that are truly relevant were looked at? I'm not going to look at the passed one anyway.

**Comment by roydahan** [comment]
At the moment you don't look at them, at some point we can decide we look at 10% of them or something similar.

There is a static breakdown that shows investigated and not investigated per status, so why do we care about it anyway?

**Comment by mykaul** [comment]
> At the moment you don't look at them, at some point we can decide we look at 10% of them or something similar.

We are unlikely to do that. We'll always strive to do better work on the failures - work on improving their reports, reduce false-positives, improve infra issues, etc.

> 
> There is a static breakdown that shows investigated and not investigated per status, so why do we care about it anyway?

Correct me if I'm wrong - but if we have a mix of passed and failed issues, the 'box' around the test won't disappear until all issues are marked as 'investigated', no?

**Comment by roydahan** [comment]
> Correct me if I'm wrong - but if we have a mix of passed and failed issues, the 'box' around the test won't disappear until all issues are marked as 'investigated', no?

Yes, and this is an actual issue we can fix.

**Comment by mykaul** [comment]
> > Correct me if I'm wrong - but if we have a mix of passed and failed issues, the 'box' around the test won't disappear until all issues are marked as 'investigated', no?
> 
> Yes, and this is an actual issue we can fix.

OK - that's a good path then.

**Comment by roydahan** [comment]
The only usability issue is with two runs that have "Failed" and "Passed" and after the failed is set as investigated, the "Passed" one still affects the run status.
@k0machi any suggestion on how to solve it?

**Comment by k0machi** [comment]
We found an issue related to this where bug/comment/investion status would not be set properly for aggregated runs such as rolling upgrade - a failed run could show not investigated if a passed run occured later - will be fixing this issue as part of the ticket, which should solve this problem.
