### ISSUE TITLE
Bug template - have the Version of Scylla appear at the top of the bug description

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#324]
When using the template, the Scylla version (https://github.com/scylladb/argus/blob/220c6a4a44b3c7d9addeb1e2c808b4e93fe61782/frontend/TestRun/IssueTemplate.svelte#L143 ) appears way below a lot of text.
I think it makes a lot of sense to move it higher up - so we can start by understanding which Scylla version we are talking about.

**Comment by mykaul** [comment]
> want to move all the versions from `Installation Details` to before the `Issue description` section ?
> 
> sounds reasonable to me

I'm usually first and foremost need the Scylla version (TBH, I would want it in the title  some day, or via a label, ...)

**Comment by roydahan** [comment]
I agree as well.

**Comment by fruch** [comment]
Using the query parameters, Argus would be able to fill a template to the title, and labels 

https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query
