### ISSUE TITLE
Unsupported plugin #empty-test-name

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#325]
I've added the SCT plugin to https://argus.scylladb.com/workspace?state=WyIxYzNhZThhMi0xNjhhLTQxOGItOTIyOS0yYzNmOWVkMjNhZmUiXQ - I hope it's OK - who should have done it?

**Comment by fruch** [comment]
As @k0machi answer, 

that would be update automatically, once there a 1st run, before that Argus doesn't know anything about that jenkins job.
