### ISSUE TITLE
RFE - Detailed statuses to become quick filters 

### ISSUE THREAD

**Issue by roydahan** [scylladb/argus#328]
When looking at the release board, we have the detailed statistics of the jobs for "Investigated", "In Progress", etc.
It would be great if these would be a quick filters (either in the same screen or link to "workspace" screen for all relevant jobs.

**Comment by fruch** [comment]
Maybe a bit overlapping with: https://github.com/scylladb/argus/issues/352

**Comment by roydahan** [comment]
I don't think so.
Here it's more of usability, when you see "failures", you just want to quickly select all of them.
It doesn't affect the view.
