### ISSUE TITLE
"An error occurred" after clicking on a release on the menu on the left

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/argus#350]
![Screenshot from 2024-04-11 14-11-10](https://github.com/scylladb/argus/assets/120044486/550dac6f-620a-422f-94d6-21d0bd088ca8)

Browser: firefox 117.0.1 (64-bit)
to reproduce:
load https://argus.scylladb.com/workspace
click on the left e.g. scylla-master

Unfortunately it doesn't reproduce every time

**Comment by k0machi** [comment]
It's a known issue, due to how scheduling information is handled in the backend, affecting large folders like `master` or `staging`. The error is benign - what fails to load are profile pictures of people 'assigned' to nested folders within that folder.
