### ISSUE TITLE
RFE - "User View" feature - ability to define a "view" that present a user only certain things

### ISSUE THREAD

**Issue by roydahan** [scylladb/argus#352]
As there are different users to Argus and each cares about different things, I'm suggesting a new method of looking at things with regards to releases.
(In general it can be relevant to cross releases in cases like performance, but for now we can focus on views inside of releases).

The way I imagine that is an ability to pick a widget (e.g. "All issues", "Status Bar", "Jobs Last status" and more when we invent them), for each widget we will be able to define the way to filter, group and sort (E.g. filter only jobs I care when I work on a patch release, or group the jobs by type, assignee, etc).

Main use cases I see:
1. "ALL" (our current view under a release) where we have all widgets and all jobs, grouped by their Jenkins folder.
2. "Patch Release" - a view that filters only the jobs that should be auto triggered for a patch release.
3. "Release Engineering" - a view that filters only the jobs releng team cares about (e.g. their jobs + dtest + auto triggered jobs).
4. "Standard User" - only his staging jobs / reproducers jobs.

**Comment by roydahan** [comment]
@k0machi let's have it discussed in our weekly meeting next week.

**Comment by k0machi** [comment]
Work in progress PR #374
