### ISSUE TITLE
Easier planning of testing (specific field for planned RC, copy from other release?)

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#376]
So people can plan better what todo inside a release we should be able to:

```[tasklist]
### Tasks
- [ ] copy a plan from previous release/s
- [x] multiple select and update target release
```

**Comment by roydahan** [comment]
Also, we would want to set in advance each test in which RC it will run and eventually to be able to automatically trigger those (integration with scylla-pkg I guess) based on the RC.
