### ISSUE TITLE
Ability to clone jobs that doesn't have runs

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#379]
For testing purposes people should be able to clone job into staging, from job that doesn't have any runs.

for example from the individual nemesis folder, where we don't keep running all of them, but still we want people to be able to clone those and give it the first run.

(as a worked around, I have to run on master until I got one run that start, and then I could clone, but that's waste of time and resources)

**Comment by k0machi** [comment]
Should be somewhat simple to do, with a small caveat - I think the clone/rebuild modal doesn't have the fallback logic for empty jobs, so that's the only thing needs to be added before a button can be exposed on empty runs.
