### ISSUE TITLE
job scanning should identify release folders, and scan them

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#390]
we shouldn't be doing any manual work, for a new release of scylla in argus.

SCT jobs should be identified, and marked as SCT plug-in, it shouldn't be manual

**Comment by k0machi** [comment]
As I've proposed last month, it should do a regex scan instead of exact match, should be a quick fix.

**Comment by fruch** [comment]
> As I've proposed last month, it should do a regex scan instead of exact match, should be a quick fix.

So let's do it, it's slowing down work on releases, every time there's new release, and no one exactly knows how to make it visible in Argus

**Comment by fruch** [comment]
Also let's have this list of regex somewhere in the code, so we can track changes, and not on configuration that exist and get edited only where the webapp is
