### ISSUE TITLE
Can't select multiple test with the same name into a view

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#413]
once you select two tests with same name (that are in different folder/group), view only show one of them.
when you go to edit the view, you see two identical ones entries for one group, and not from the other.

**Comment by k0machi** [comment]
Can you provide the reproduction steps? I've tried selecting two tests with the same name from different folders in the same release (and different release as well) and it worked for me - the option should be using test's id, which is always unique

**Comment by fruch** [comment]
> Can you provide the reproduction steps? I've tried selecting two tests with the same name from different folders in the same release (and different release as well) and it worked for me - the option should be using test's id, which is always unique

now I've got it to work

but it's really confusing, since when you select there's the name of the group/folder, but once you load it up, the group/folder isn't showing, so you can know what is what

**Comment by fruch** [comment]
it was partly cause I could also found the one I'm looking for.

**Comment by fruch** [comment]
seems like it's now working,

the issue was a bug in test collection
