### ISSUE TITLE
Add description to groups

### ISSUE THREAD

**Issue by pehala** [scylladb/argus#428]
Currently, there is a lot of groups, but it hard to know what each of the groups should be doing. I think we need some transparency over that. For example, there are longevity tests that run only 12H but you cannot read that information anywhere

My proposal is to add a description to each group, where we could define a description so that everyone that is not that familiar with SCT could understand why this group exists and what are the specifics.

**Comment by fruch** [comment]
My suggestion is as follows:
1) we'll add file with description in each folder in SCT
2) SCT would be change to apply this description into jenkins job description
3) Argus would read those during scan of jobs, and save it
4) Argus would should those a tooltips

bonus:
- argus to have a way to edit those - (but not sure it would be wise, since it would eventually get out of sync with the source in SCT)

**Comment by pehala** [comment]
> we'll add file with description in each folder in SCT

Could we create one file for Argus all metadata (e.g. name, description) instead? I am not sure that adding yet another file that contains only one piece of information is a good idea. 
Also it would be easier to have one file so that we could easily add additional metadata in the future, just by adding more fields to existing file

**Comment by fruch** [comment]
> > we'll add file with description in each folder in SCT
> 
> Could we create one file for Argus all metadata (e.g. name, description) instead? I am not sure that adding yet another file that contains only one piece of information is a good idea. Also it would be easier to have one file so that we could easily add additional metadata in the future, just by adding more fields to existing file

that file won't reach argus directly, i.e. it would be used to update the job.

one file is better yes, but now it's need to have a format, and it might  complex backporting a bit

**Comment by soyacz** [comment]
@fruch is it really fixed? we still miss these files and support in Argus for that
