### ISSUE TITLE
Add ability to hide not planned tests

### ISSUE THREAD

**Issue by pehala** [scylladb/argus#429]
A fair share of tests are not planned for specific release (~190 for 2024.2) and as such are not planned, however, they still show at the list, which creates visual clutter and can be severely confusing for a newcomer (like me).

I propose adding an option to hide not planned tests and groups that contain only not planned test either as user option or a general button on a site

**Comment by fruch** [comment]
@pehala 

you are referring to "not planned" ones ?

**Comment by pehala** [comment]
Yes, sorry for the confusion, I updated name and the description
