### ISSUE TITLE
Rename skipped tests to not planned

### ISSUE THREAD

**Issue by pehala** [scylladb/argus#430]
As far as I know, `skipped` tests are `not planned` tests. When I first encountered this I did not realize it and caused unnecessary confusion.

I propose renaming `skipped` to `not planned`. I think that better indicates what we actually mean by `skipped` test.

**Comment by fruch** [comment]
@pehala 

where did you see the word skip exactly ?

![Image](https://github.com/user-attachments/assets/9873a48d-ebca-4e0d-a88c-6425cbf5da58)

context here (i.e. picture), would help understand what exactly is the suggestion

**Comment by pehala** [comment]
Sorry, I got confused, I mistook `not planned` with `skipped` in nemesis (where it is shown in Nemesis tab) and assumed that everything is called "skipped". Naming makes sense in Nemesis tab and testcases already use not planned. Closing this.
