### ISSUE TITLE
Can't rebuild - version string is incorrectly marked as wrong

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#451]
I'm trying to rebuild https://argus.scylladb.com/test/854158d6-db2f-4365-a140-553fac97e1b4/runs?additionalRuns%5B%5D=aaca5e42-b630-4640-a645-a5dec65a1143 and getting the following:
![image](https://github.com/user-attachments/assets/174a4cde-1056-480c-b038-9a63447aad91)

**Comment by k0machi** [comment]
Has the version string been changed in SCT/scylla? I see there's a dash `-` now instead of `~`, which iirc wasn't a thing before.

**Comment by k0machi** [comment]
Actually, the test failed previously precisely because the version string is wrong - it should have tilde instead of a dash before rc marker.

**Comment by mykaul** [comment]
> Has the version string been changed in SCT/scylla? I see there's a dash `-` now instead of `~`, which iirc wasn't a thing before.

That's a bit odd. Why would anyone use ~ sign?

**Comment by k0machi** [comment]
> Actually, the previous test failed precisely because the version string is wrong - it should have tilde instead of a dash before rc marker.

Nevermind, that is wrong - it seems that promotion in Azure didn't happen? Both `-` and `~` don't work.



> > Has the version string been changed in SCT/scylla? I see there's a dash `-` now instead of `~`, which iirc wasn't a thing before.
> 
> That's a bit odd. Why would anyone use ~ sign?

Scylla reports it that way, but it looks like we do it both ways - I'll add `-` as a valid version separator then.

**Comment by mykaul** [comment]
@yaronkaikov claimed promotion did take place.

**Comment by k0machi** [comment]
For now you can switch to `All parameters` tab and build from there - validation doesn't happen on that tab. I'm trying to start it again with `2022.2.0-rc2`

**Comment by k0machi** [comment]
> For now you can switch to `All parameters` tab and build from there - validation doesn't happen on that tab. I'm trying to start it again with `2022.2.0-rc2`

Aand it doesn't work:
```
13:10:19  ValueError: Azure Image for scylla_version='2024.2.0-rc2' not found in eastus
```

**Comment by mykaul** [comment]
> > For now you can switch to `All parameters` tab and build from there - validation doesn't happen on that tab. I'm trying to start it again with `2022.2.0-rc2`
> 
> Aand it doesn't work:
> 
> ```
> 13:10:19  ValueError: Azure Image for scylla_version='2024.2.0-rc2' not found in eastus
> ```

@yaronkaikov ?

**Comment by yaronkaikov** [comment]
@k0machi where are you trying to take the image? from the marketplace?

**Comment by k0machi** [comment]
> @k0machi where are you trying to take the image? from the marketplace?

I'm not sure, I don't think we are using marketplace to retrieve image for SCT. @fruch @soyacz

**Comment by fruch** [comment]
@yaronkaikov 

yes we are taking it from  `CommunityGalleries`:
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                             Azure Machine Images by version                                                             |
+---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
| Backend | Name     | ImageId                                                                                                             | CreationDate |
+---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
| Azure   | 2024.2.0 | /CommunityGalleries/scylladb-7e8d8a04-23db-487d-87ec-0e175c0615bb/Images/scylla-enterprise-2024.2/Versions/2024.2.0 | N/A          |
+---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
```

but there's only 2024.2.0, no version named 2024.2.0~rc2

**Comment by yaronkaikov** [comment]
> @yaronkaikov
> 
> yes we are taking it from `CommunityGalleries`:
> 
> ```
> +---------------------------------------------------------------------------------------------------------------------------------------------------------+
> |                                                             Azure Machine Images by version                                                             |
> +---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
> | Backend | Name     | ImageId                                                                                                             | CreationDate |
> +---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
> | Azure   | 2024.2.0 | /CommunityGalleries/scylladb-7e8d8a04-23db-487d-87ec-0e175c0615bb/Images/scylla-enterprise-2024.2/Versions/2024.2.0 | N/A          |
> +---------+----------+---------------------------------------------------------------------------------------------------------------------+--------------+
> ```
> 
> but there's only 2024.2.0, no version named 2024.2.0~rc2

yes, this is because Azure won't accept `-rcX` or `~rcX` so until we have an official release, we override this so 2024.2.0 is now `rc2`
