### ISSUE TITLE
'Restore Monitoring Stack' - should restore in the correct timeframes of the test

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#454]
The restore monitoring stack (which is a Jenkins job - so perhaps this is not the best place to file this?) should give not just a link to the Grafana, but also already within the time frame (Start - Finish) of the Argus job it ran.
The data is there, it needs to be passed as parameters .

**Comment by k0machi** [comment]
Coincides with https://github.com/scylladb/scylla-cluster-tests/issues/5045 - Yes, we could potentially use Argus for this.

**Comment by soyacz** [comment]
doing it in https://github.com/scylladb/scylla-cluster-tests/pull/8921
It's going to be part of dashboard configuration (updated upon test teardown).
I think it's the easiest and convenient way (no impact on url's), but all the previous snapshots won't be updated.
