### ISSUE TITLE
Performance results - cycles - should show time (so we can correlate the cycles to the logs)

### ISSUE THREAD

**Issue by mykaul** [scylladb/argus#455]
Example:
![image](https://github.com/user-attachments/assets/56360b0c-57fa-465e-bd1d-f8202eb1321a)

How do I know when did cycle 2 took place?
Taken from https://argus.scylladb.com/test/3ec1793e-7b3f-4b15-b10f-8dab7bb83cde/runs?additionalRuns%5B%5D=a2dac2ad-0ab6-4399-9c8d-b08fcdbc6198

**Comment by mykaul** [comment]
> We don't track it in results (yet?). But in recent runs, we started to supply monitoring screenshots - where you can read timings from. Is it enough?

![image](https://github.com/user-attachments/assets/5ee31285-bd62-47b3-a746-80e1d7557108)

**Comment by soyacz** [comment]
![image](https://github.com/user-attachments/assets/2bbd5c0b-f8fa-40ae-bc73-dd36fc5ec165)

**Comment by fruch** [comment]
> > We don't track it in results (yet?). But in recent runs, we started to supply monitoring screenshots - where you can read timings from. Is it enough?
> 
> ![image](https://private-user-images.githubusercontent.com/4655593/368117066-5ee31285-bd62-47b3-a746-80e1d7557108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Njc2ODMsIm5iZiI6MTcyNjU2NzM4MywicGF0aCI6Ii80NjU1NTkzLzM2ODExNzA2Ni01ZWUzMTI4NS1iZDYyLTQ3YjMtYTc0Ni04MGUxZDc1NTcxMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTAwMzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODMyMjJjZDg5MmMxZjY4ODkyY2YyNjU3NmQxYzIxNTMwYTZjYTk3YzkzZmE3ZjIzZjExMTA0YzBmODc0ZGZjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RYeRXzOd3tCm5zXq50huRRBB4u4qO63HYZ26EE1Gn2c)

@mykaul you are looking at a run that we had a bug still with the report of screenshots, and we didn't had a screen report per operation.

the information is in the email report, look up `a2dac2ad-0ab6-4399-9c8d-b08fcdbc6198` in emails, and you'll see it.

we are in the process of moving all of those into Argus, we are 90% there, but old results might not have it all
