### ISSUE TITLE
Cell.__init__() got an unexpected keyword argument 'value_text'

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/argus#461]
## Packages

Scylla version: `2024.1.10-20240918.24a78645ca8b` with build-id `ee974e7eb45c7a3007c99f53b7ccd7ce54dcd23c`
Kernel Version: `5.15.0-1070-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The test failed with error:

```
2024-09-24 13:58:24.992: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=827149b1-2213-4229-b349-ab0177eae252, source=PerformanceRegressionPredefinedStepsTest.test_mixed_gradual_increase_load (performance_regression_gradual_grow_throughput.PerformanceRegressionPredefinedStepsTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/performance_regression_gradual_grow_throughput.py", line 36, in test_mixed_gradual_increase_load
self._base_test_workflow(cs_cmd_tmpl=self.params.get('stress_cmd_m'),
File "/home/ubuntu/scylla-cluster-tests/performance_regression_gradual_grow_throughput.py", line 73, in _base_test_workflow
self.run_gradual_increase_load(stress_cmd_templ=cs_cmd_tmpl,
File "/home/ubuntu/scylla-cluster-tests/performance_regression_gradual_grow_throughput.py", line 163, in run_gradual_increase_load
results = run_step(stress_cmds=stress_cmd_templ, current_throttle=current_throttle,
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 271, in wrapped
send_result_to_argus(
File "/home/ubuntu/scylla-cluster-tests/sdcm/argus_results.py", line 135, in send_result_to_argus
argus_client.submit_results(result_table)
File "/usr/local/lib/python3.10/site-packages/argus/client/base.py", line 224, in submit_results
self.check_response(response)
File "/usr/local/lib/python3.10/site-packages/argus/client/base.py", line 68, in check_response
raise ArgusClientError(
argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/testrun/scylla-cluster-tests/253d4698-6509-4b08-906c-d6815bb4a04f/submit_results', "Cell.__init__() got an unexpected keyword argument 'value_text'")
```

The failure happened from `@latency_calculator_decorator` 

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- perf-regression-predefined-steps-ub-db-node-253d4698-3 (34.251.84.207 | 10.4.7.190) (shards: 14)
- perf-regression-predefined-steps-ub-db-node-253d4698-2 (3.249.5.103 | 10.4.4.199) (shards: 14)
- perf-regression-predefined-steps-ub-db-node-253d4698-1 (52.210.151.97 | 10.4.6.35) (shards: 14)

OS / Image: `ami-083b92d3782b9a373` (aws: undefined_region)

Test: `scylla-enterprise-perf-regression-scylla-predefined-steps-vnodes.jenkinsfile`
Test id: `253d4698-6509-4b08-906c-d6815bb4a04f`
Test name: `scylla-staging/yulia/performance/scylla-enterprise-perf-regression-scylla-predefined-steps-vnodes.jenkinsfile`
Test method: `performance_regression_gradual_grow_throughput.PerformanceRegressionPredefinedStepsTest.test_mixed_gradual_increase_load`
Test config file(s):

- [perf-regression-predefined_steps.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/28e5597cfa68842e68022dc9e29f60dad49ad4c5/test-cases/performance/perf-regression-predefined_steps.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 253d4698-6509-4b08-906c-d6815bb4a04f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=253d4698-6509-4b08-906c-d6815bb4a04f)
- Show all stored logs command: `$ hydra investigate show-logs 253d4698-6509-4b08-906c-d6815bb4a04f`

## Logs:
- **db-cluster-253d4698.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/db-cluster-253d4698.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/db-cluster-253d4698.tar.gz)
- **sct-runner-events-253d4698.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/sct-runner-events-253d4698.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/sct-runner-events-253d4698.tar.gz)
- **sct-253d4698.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/sct-253d4698.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/sct-253d4698.log.tar.gz)
- **loader-set-253d4698.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/loader-set-253d4698.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/loader-set-253d4698.tar.gz)
- **monitor-set-253d4698.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/monitor-set-253d4698.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/253d4698-6509-4b08-906c-d6815bb4a04f/20240924_140104/monitor-set-253d4698.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/performance/job/scylla-enterprise-perf-regression-scylla-predefined-steps-vnodes.jenkinsfile/2/)
[Argus](https://argus.scylladb.com/test/eb4c6587-c82f-4add-8422-eee040660768/runs?additionalRuns[]=253d4698-6509-4b08-906c-d6815bb4a04f)
</details>

**Comment by soyacz** [comment]
Should be fixed in https://github.com/scylladb/argus/pull/460
