### ISSUE TITLE
Add ability to exclude result

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#462]
Sometimes result sent to argus might be wrong, and break how graphs look (introducing unnecessary noise) or spoil "best result" and affecting validation.
We need a method to remove such results easily.
Open questions:
1. Should it be per run (e.g. removing/disabling whole run result) or single one?
2. Shall it revalidate all the next results (if 'best_result' was affected)?

My proposal is to add a button in "results" tab to mark all tables as "spoiled" (something like "Disable" button with graph icon).

**Comment by soyacz** [comment]
@fruch , @juliayakovlev proposed to use `IGNORED` job status to exclude result.
I think it's good idea. WDYT?
Also, I'll need to push https://github.com/scylladb/argus/pull/476 forward as it messes with the same parts of code (and some will be reused) to make this one happen.

**Comment by juliayakovlev** [comment]
> [@fruch](https://github.com/fruch) , [@juliayakovlev](https://github.com/juliayakovlev) proposed to use `IGNORED` job status to exclude result. I think it's good idea. WDYT? Also, I'll need to push [#476](https://github.com/scylladb/argus/pull/476) forward as it messes with the same parts of code (and some will be reused) to make this one happen.

Actually it's Israel's idea )

**Comment by fruch** [comment]
> > [@fruch](https://github.com/fruch) , [@juliayakovlev](https://github.com/juliayakovlev) proposed to use `IGNORED` job status to exclude result. I think it's good idea. WDYT? Also, I'll need to push [#476](https://github.com/scylladb/argus/pull/476) forward as it messes with the same parts of code (and some will be reused) to make this one happen.
> 
> Actually it's Israel's idea )

it was @roydahan idea, we are just passing along the message :)

**Comment by fruch** [comment]
I think matches the reason of what is ignore meant to be, and not we have a practical usage of it.

it solve the UX around this one, kind of nicely.
and yet again introduce a reason for us to load the runs data. (we have plenty of those reasons)
