### ISSUE TITLE
Please, add a link to open an issue in Argus

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/argus#465]
Please, add a link to open an issue in Argus

**Comment by soyacz** [comment]
shouldn't it be 4 links? Scylla enterprise, oss, SCT and Argus?

**Comment by fruch** [comment]
Now it only shows 3 of them:

![Image](https://github.com/user-attachments/assets/f9735503-d839-4ba0-b62f-3cc891336597)

we should add argus.
