### ISSUE TITLE
Show more runs (+ icon) does not work sometimes

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#483]
See https://argus.scylladb.com/workspace?state=WyIxZTRjZDc0My1hN2U0LTQ0M2EtYjAzMy03Y2EyOWFiMGZlOWIiXQ
despite having more runs that 4 and 5, cannot expand them (also only these 2 are visible), but when looking into graphs there are 3 results available and when clicking one, runs list expands by it.

https://argus.scylladb.com/api/v1/test/1e4cd743-a7e4-443a-b033-7ca29ab0fe9b/runs?limit=20 endpoint returns only 2.

**Comment by fruch** [comment]
@k0machi 

can you check this out ?

seems like we can get to those result if we use the specific test ids

**Comment by k0machi** [comment]
This test was renamed and old runs are accessible under old name (which is now hidden)
![Image](https://github.com/user-attachments/assets/a40031f5-923e-4f07-b2ed-7aa5b302fb68)

![Image](https://github.com/user-attachments/assets/4901e341-3c5a-429c-8d20-3ebb448a1d18)

**Comment by k0machi** [comment]
> how can a test be renamed ? in jenkins ?
> 
> again someone delete something from argus ?

Renamed in jenkins, old test is still there, new test was created automatically after rename.
