### ISSUE TITLE
Feature Request: Collaborative Discussions for Argus Views

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#485]
### Summary:
When working with Argus Views, users often need to discuss and annotate findings during meetings. The proposed feature introduces a widget with two sections to help users highlight important messages and track action items. This will streamline collaboration, especially when analyzing the latest Argus View.

### Feature Details:

The widget consists of two sections:

1. **Highlights**  
   A place to add important messages and questions for discussion. Each entry may include:
   - Textual entries for general messages or questions. Examples:  
     - “New gradual throughput test added”  
     - “An issue was fixed/added”  
     - “Shall we test tablets with test X?”
   - Links to issues from the tracking system. These should display the issue number, title, status, and assignee.

2. **Action Items**  
   A to-do list for tasks that need action. Each action item will contain:
   - A checkbox to mark completion.
   - A textual description of the task.
   - An assigned person responsible for the task.  
   Example:  
   `[ ] | Schedule tablets test execution every 3 weeks | soyacz`

### Key Features:

- **Entry Creator**  
   Each entry (both in Highlights and Action Items) will display the creator's avatar to the left of the entry. Hovering over the avatar will show the creator's name in a tooltip. When an entry is edited, the avatar and name will update to reflect the current editor.

- **Archiving**  
   Each highlight or action item can be archived using a button next to the entry. Archived entries will be hidden from the default view but can be shown again via a "Show Archived" button. This button will display only the 30 most recently archived items, with the possibility to unarchive them.

- **Comments**  
   Each entry (both in Highlights and Action Items) can have multiple comments. Comments will be:
   - Collapsible and collapsed by default. The number of comments will be visible, and an expand button will allow users to see them.
   - Editable and deletable only by the original comment creator.
   - No nested comments (i.e., comments on comments) for now.

- **Editing**  
   All users can create and edit own entries.

- **Sorting**  
   Action items will be ordered by their creation time. There are no due dates or priority levels at this time.

Refs: https://github.com/scylladb/qa-tasks/issues/1784

**Comment by soyacz** [comment]
@roydahan @fruch please review if this makes sense and is targeting our needs for discussions (results summary, graphing will be in separate widgets).

**Comment by soyacz** [comment]
Draft widget (no backend logic still, just to show how I imagined it more-or-less):
Clicking comment button expands comments (one expanded as an example), also clicking show archived will show archived ones with gray background.
![Image](https://github.com/user-attachments/assets/71ffc038-c59c-48b4-9a51-428d07834b3e)

@fruch @roydahan @k0machi WDYT?

**Comment by k0machi** [comment]
You can probably reuse the comment editor component for creating comments, other than that, looks good

**Comment by soyacz** [comment]
cc @kwiato

**Comment by fruch** [comment]
> Draft widget (no backend logic still, just to show how I imagined it more-or-less):
> Clicking comment button expands comments (one expanded as an example), also clicking show archived will show archived ones with gray background.
> ![Image](https://github.com/user-attachments/assets/71ffc038-c59c-48b4-9a51-428d07834b3e)
> 
> @fruch @roydahan @k0machi WDYT?

Looks good Frank :)

We should have a way to clear item from highlight

Maybe we want comment and action items separated ? or have a way to convert a comment to action item ?

**Comment by soyacz** [comment]
> Looks good Frank :)
> 

:) 

> We should have a way to clear item from highlight

there's "archive" button - it hides away given item (can be shown back with "show archived")

> 
> Maybe we want comment and action items separated ? or have a way to convert a comment to action item ?

Comments are meant for specific highlight/action item to have discussion about them. I'm not sure how comments out of context would be useful. 
Converting is a thing to consider, but later, when we see it's really needed (I'm afraid that comment form is not fitting to action item/highlight).
