### ISSUE TITLE
Feature Request: Performance Summary View Widget

### ISSUE THREAD

**Issue by soyacz** [scylladb/argus#486]
### Problem:
In Argus View, identifying failed test results from the current week is challenging due to the large number of tests and runs. Users must also navigate into test run details to view failed result tables, making it difficult to grasp failures at a glance. Additionally, important tested versions can be buried in the results.

### Proposed Solution:
A widget will be developed to simplify the view of weekly test results, emphasizing failures and presenting failure details upfront, without requiring the user to open test run details. It will also provide better visibility into both passed and failed tests.

### Widget Features:

1. **One widget per release**:
   - The widget will configured to summarize only one release.
   - Summary will be provided per Scylla version in given release (e.g. dev, 2024.2, 6.2 etc.)
   - User will be able to go back to previous versions (select from list containing exact version and build date or with arrow buttons to go back to previous/next ones). Ordered by Scylla build date.

2. **Highlighting missed tests**:
   - Tests that were not executed for given version or failed to start (e.g., due to infrastructure issues like AWS capacity) will be highlighted at the top of the widget (when there's no metric results).
   - These tests will be treated as failures.

3. **Test Run Lists**:
   - Widget will contain test runs segregated into two collapsible lists:
     - **Failed List**: Displays all failed test runs and their failed result tables (expanded by default). 
     - **Passed List**: Displays all successfully passed test runs (collapsed by default).
   - tests may use different test methods - each test method results should be shown in own column (3 maximum) 
   - Each test run in both lists will be clickable, allowing users to navigate to the detailed test run page if needed.
   - Each test run entry will show:
     - values of selected metrics (`key metrics`) in tabular form, with columns: result table name, and rest will be selected metrics names
     - The **count of error events** associated with that test run.
     - **Failed result tables** will be displayed (collapsed by default for passed tests, visible for failed tests).
of the error count and the failed result tables (collapsed by default).

4. **Run Investigation Status**:
   - Any test runs marked as "IGNORED" in their investigation status will be excluded from the analysis to avoid clutter.
   - Test runs that have failed result tables or error events but are manually marked as passed will still be listed in the passed list, with an indication 

5. **Widget Configuration**:
   - Users can configure the widget by:
     - Setting a name (e.g. summary - vnodes based tests, summary - tablets based tests)
     - Setting release to analyze (e.g. 2024.2, 6.2)
     - Selecting which tests to monitor from the available test groups.
     - selected metric values (e.g. p99's, duration of repair etc.)
   - Widgets can be edited at any time to add/remove tests or change the name.

refs: https://github.com/scylladb/qa-tasks/issues/1784

**Comment by soyacz** [comment]
[summary-widget.html.zip](https://github.com/user-attachments/files/17804253/summary-widget.html.zip)
@fruch please take a look basic layout (autogenerated, mostly showing just layout as how it will look in detail will change).

**Comment by soyacz** [comment]
> > [summary-widget.html.zip](https://github.com/user-attachments/files/17804253/summary-widget.html.zip) [@fruch](https://github.com/fruch) please take a look basic layout (autogenerated, mostly showing just layout as how it will look in detail will change).
> 
> looks like a good start, I would rather see it with less clicks failures should be open to begin with.
> 

Yes, I was planning it.

> It's kind of missing showing all the types (read/mixed/write) side by side.

Ok, I'll try that as I need to see if it will fit into screen width.
Still I'm not yet sure how to handle period for summary - hardcode 1 week, make it configurable, or just most recent jobs (which will be harder in case of partial rerun e.g. repeat mixed test).
Also I wonder if shouldn't support going back to previous summaries.

> 
> [@roydahan](https://github.com/roydahan) [@juliayakovlev](https://github.com/juliayakovlev), care to take a look ?

**Comment by fruch** [comment]
> > > [summary-widget.html.zip](https://github.com/user-attachments/files/17804253/summary-widget.html.zip) [@fruch](https://github.com/fruch) please take a look basic layout (autogenerated, mostly showing just layout as how it will look in detail will change).
> > 
> > 
> > looks like a good start, I would rather see it with less clicks failures should be open to begin with.
> 
> Yes, I was planning it.
> 
> > It's kind of missing showing all the types (read/mixed/write) side by side.
> 
> Ok, I'll try that as I need to see if it will fit into screen width. Still I'm not yet sure how to handle period for summary - hardcode 1 week, make it configurable, or just most recent jobs (which will be harder in case of partial rerun e.g. repeat mixed test). Also I wonder if shouldn't support going back to previous summaries.

If we continue with direction of running release ontop the same jobs, we'll need also to filter only dev (or specific releases)

as for going back, it's something we are doing quite a lot with current google doc, one can argue the graph can help with that bit
I don't know if we want to take off the table yet...


> 
> > [@roydahan](https://github.com/roydahan) [@juliayakovlev](https://github.com/juliayakovlev), care to take a look ?

**Comment by soyacz** [comment]
> If we continue with direction of running release ontop the same jobs, we'll need also to filter only dev (or specific releases)
> 
> as for going back, it's something we are doing quite a lot with current google doc, one can argue the graph can help with that bit I don't know if we want to take off the table yet...

So, after rethinking, idea is to add summary widget per release (upon adding widget configure which release to monitor - dev, enterprise-dev, 2024.2, 6.2 etc.).
Additionally, user will be able to scroll to previous tested versions back and forth (right-left arrows next to version, build date)

WDYT?
