### ISSUE TITLE
Is it possible to add to the Logs tab the button, that can run `hydra investigate show-logs test_id` and insert all logs into the tab?

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/argus#513]
In the test (see below) logs were collected but "Logs" tab in the Argus is empty
Is it possible to add to the Logs tab the button, that can run like `hydra investigate show-logs test_id` and insert all logs into the tab?

## Packages

Scylla version: `6.3.0~dev-20241119.733a4f94c7b2` with build-id `89a16d00ef82b3c15eb73e944afc60f15c478452`

Kernel Version: `6.8.0-1019-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-nemesis-ubuntu-db-node-2805dd59-3 (34.250.233.74 | 10.4.11.251) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-2805dd59-2 (54.74.124.94 | 10.4.8.78) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-2805dd59-1 (3.248.184.8 | 10.4.10.113) (shards: 7)

OS / Image: `ami-0d782b5935da36d59` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-with-nemesis`
Test id: `2805dd59-bc75-4611-bf02-dd3395f6dc57`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis`
Test method: `performance_regression_test.PerformanceRegressionTest.test_latency_write_with_nemesis`
Test config file(s):

- [perf-regression-latency-650gb-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c124bfd47fdfcd23fab85a2fc1ddd011650b2e3f/test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2805dd59-bc75-4611-bf02-dd3395f6dc57`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2805dd59-bc75-4611-bf02-dd3395f6dc57)
- Show all stored logs command: `$ hydra investigate show-logs 2805dd59-bc75-4611-bf02-dd3395f6dc57`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-with-nemesis/30/)
[Argus](https://argus.scylladb.com/test/4f088858-cbf2-4984-9d44-d319c207f521/runs?additionalRuns[]=2805dd59-bc75-4611-bf02-dd3395f6dc57)
</details>

**Comment by k0machi** [comment]
The newly added `hydra <...> show-logs --update-argus` should help with this.

https://github.com/scylladb/scylla-cluster-tests/pull/9003
