### ISSUE TITLE
argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/sct/27fc85e6-772f-4b14-a297-bc7a79384843/packages/submit', 'Run not found'

### ISSUE THREAD

**Issue by Lakshmipathi** [scylladb/argus#526]
First cloned the job via jenkins UI. After jenkins run failed, I did clone via argus UI. It said `job already exists`.  Then renamed the existing job as `OLD_scylla-enterprise-perf-regression-latency-650gb-elasticity` and cloned again.  clone succeeded and while running the job, it failed message:

`argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/sct/27fc85e6-772f-4b14-a297-bc7a79384843/packages/submit', 'Run not found')`

**Comment by k0machi** [comment]
Closing in favor of #543
