### ISSUE TITLE
API error when pasting in github issue link in dashboard > run > issues tab

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/argus#59]
Trying to paste an issue gave me the following alter:

![image](https://user-images.githubusercontent.com/13716678/159033275-594fb3a0-5f8c-49a4-9d96-474f1f1ec672.png)

**Comment by k0machi** [comment]
https://github.com/scylladb/argus/blob/master/argus/backend/argus_service.py#L614

Looks like I've missed this one when refactoring how test names are used in argus. Will fix soon.
